networks:
  hexddd-network:
    driver: bridge

services:
  postgres:
    container_name: hexddd-postgres
    image: postgres:17.2
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=hexddd
      - POSTGRES_USER=hexddd
      - POSTGRES_DB=hexddd

  zookeeper:
    image: bitnami/zookeeper:3.9.1
    container_name: hexddd-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181
    networks:
      - hexddd-network

  kafka:
    image: bitnami/kafka:3.6.1
    container_name: hexddd-kafka
    environment:
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CFG_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_CFG_NUM_NETWORK_THREADS: 16
    ports:
      - 9092:9092
    expose:
      - 9093
    networks:
      - hexddd-network
    depends_on:
      - zookeeper

  cdvs-kafka-ui:
    container_name: hexddd-kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9090:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CFG_CLUSTERS_0_NAME: local
      KAFKA_CFG_CLUSTERS_0_BOOTSTRAPSERVERS: hexddd-kafka:9093
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - hexddd-network

volumes:
  pgdata: