name: Maven default workflow

on:
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run tests
      run: mvn verify --file pom.xml
